apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charity
  template:
    metadata:
      labels:
        app: charity
    spec:
      containers:
      - name: charity-pod
        image: demoregistry2211.azurecr.io/charity:latest
        env:
        - name: DATABASE_HOST
          value: <enter-your-host>
        - name: DATABASE_PORT
          value: "<enter-your-port>"
        - name: DATABASE_NAME
          value: charity
        - name: DATABASE_USERNAME
          value: <enter-your-username>
        - name: DATABASE_PASSWORD
          value: <enter-your-password>
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: media-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: media
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharecare-media-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: sharecare-media-svc
                port:
                  number: 80
            path: /media