apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-pod
        image: demoregistry2211.azurecr.io/user:latest
        envFrom:
        - secretRef:
            name: sharecare-db-secret
        env:
        - name: DATABASE_NAME
          value: user
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 150m
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: user
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharecare-user-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: user-svc
                port:
                  number: 80
            path: /users